import { GridRowsProp } from '@mui/x-data-grid'

export const rows: GridRowsProp = [
  {
    id: 1,
    group: ' ',
    work_code: '3.2.2.1',
    pavilion: '10',
    floor: '5 этаж',
    name: 'Устройство монолитных стен из бетона марки В40',
    total: '100',
    fact_month: '...',
  },
  {
    id: 2,
    group: ' ',
    work_code: '3.2.2.1',
    pavilion: '10',
    floor: '5 этаж',
    name: 'Устройство монолитных стен из бетона марки В40',
    total: '100',
    fact_month: '...',
  },
  {
    id: 3,
    group: ' ',
    work_code: '3.2.2.1',
    pavilion: '10',
    floor: '5 этаж',
    name: 'Устройство монолитных стен из бетона марки В40',
    total: '100',
    fact_month: '...',
  },
  {
    id: 4,
    group: ' ',
    work_code: '3.2.2.1',
    pavilion: '10',
    floor: '5 этаж',
    name: 'Устройство монолитных стен из бетона марки В40',
    total: '100',
    fact_month: '...',
  },
  {
    id: 5,
    group: ' ',
    work_code: '3.2.2.1',
    pavilion: '10',
    floor: '5 этаж',
    name: 'Устройство монолитных стен из бетона марки В40',
    total: '100',
    fact_month: '...',
  },
  {
    id: 6,
    group: ' ',
    work_code: '3.2.2.1',
    pavilion: '10',
    floor: '5 этаж',
    name: 'Устройство монолитных стен из бетона марки В40',
    total: '100',
    fact_month: '...',
  },
]
